#回答增加父级id，进行多层回答专用		yobi  2018/03/20
ALTER TABLE `t_faq`
ADD COLUMN `parentId`  bigint(20) NULL DEFAULT 0 COMMENT '上级ID' AFTER `amount`;

#文件管理		yobi  2018/03/22
ALTER TABLE `sys_file`
ADD COLUMN `fileName`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '文件名称' AFTER `create_date`;

#电费信息相关脚本  yobi  2018/03/30
-- ----------------------------
-- Table structure for dl_kh_khzj
-- ----------------------------
DROP TABLE IF EXISTS `dl_kh_khzj`;
CREATE TABLE `dl_kh_khzj` (
  `KHZJBS` varchar(16) NOT NULL COMMENT '客户证件的唯一标识',
  `KHBH` varchar(20) NOT NULL COMMENT '客户的唯一标识',
  `ZJLXDM` varchar(8) NOT NULL COMMENT '01 居民身份证，公安机关出具的临时身份证件\r\n            02 户口簿\r\n            03 驾驶证\r\n            04 军人证\r\n            05 企业工商营业执照\r\n            06 社会团体法人登记证书\r\n            07 购房合同\r\n            08 组织机构代码证\r\n            09 护照\r\n            10 房产证\r\n            11 产权证\r\n            12 建设规划许可证\r\n            13 土地规划许可证\r\n            14 施工许可证\r\n            15 台胞证\r\n            99 其它\r\n            ',
  `ZJMC` varchar(128) DEFAULT NULL COMMENT '证件上的名称，如身份证上的姓名',
  `ZJHM` varchar(32) DEFAULT NULL COMMENT '证件上的号码，如身份证号码',
  `ZJSXRQ` datetime DEFAULT NULL COMMENT '证件的生效时间',
  `ZJDQRQ` datetime DEFAULT NULL COMMENT '证件有效期的到期时间',
  `DQBM` varchar(8) NOT NULL COMMENT '客户所在地区，用于分区',
  `LXRBS` varchar(16) DEFAULT NULL COMMENT '联系人唯一标识',
  `GDDWBM` varchar(20) NOT NULL COMMENT '供电单位编码',
  `CJSJ` datetime NOT NULL COMMENT '数据创建时间',
  `CZSJ` datetime NOT NULL COMMENT '数据最近一次变更时间',
  `SJZYBGSJ` datetime DEFAULT NULL COMMENT '数据资源管理平台变更时间',
  `ZJZTDM` varchar(8) DEFAULT NULL COMMENT '证件状态代码',
  `BZ` varchar(256) DEFAULT NULL COMMENT '备注',
  `SHSJ` datetime DEFAULT NULL COMMENT '审核时间',
  `SHRBS` varchar(16) DEFAULT NULL COMMENT '审核人标识',
  `ZLDLDM` varchar(8) DEFAULT NULL COMMENT '资料大类代码',
  PRIMARY KEY (`KHZJBS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户的证件信息，证件包含证件类型，证件号码，证件名称，证件生效时间，证件失效时间等属性。\r\n当客户证件为联系人';

-- ----------------------------
-- Table structure for dl_kh_ydkh
-- ----------------------------
DROP TABLE IF EXISTS `dl_kh_ydkh`;
CREATE TABLE `dl_kh_ydkh` (
  `YHBH` varchar(20) NOT NULL COMMENT '用电客户的唯一编号，参见南网编码规范',
  `KHBH` varchar(20) NOT NULL COMMENT '客户的唯一标识',
  `YHMC` varchar(128) NOT NULL COMMENT '用户的名称，一般等于客户实体中的客户名称。',
  `YDDZ` varchar(128) DEFAULT NULL COMMENT '用电客户的用电地址（不可编辑，来源于结构化地址实体）',
  `XYDJDM` varchar(8) DEFAULT NULL COMMENT '通过信誉评估评估出来的用电客户的信誉等级：最高信誉度等级，较高信誉度等级，高信誉度等级，中最高信誉度等级，中较高信誉度等级等',
  `XYFZ` decimal(12,6) DEFAULT NULL COMMENT '通过信誉评估评估出来的用电客户客户的信誉分数',
  `JZDJDM` varchar(8) DEFAULT NULL COMMENT '通过价值评估评出出来的用电客户客户的价值等级：最高价值等级，较高价值等级，高价值等级，中最高价值等级，中较高价值等级等',
  `FXDJDM` varchar(8) DEFAULT NULL COMMENT '通过风险评估评估出的用电客户的风险等级：最高风险等级，较高风险等级，高风险等级，中最高风险等级，中较高风险等级等',
  `YDLBDM` varchar(8) NOT NULL COMMENT '用电客户的用电类别代码',
  `DYDJDM` varchar(8) NOT NULL COMMENT '用电客户的电压等级代码',
  `HYFLDM` varchar(8) DEFAULT NULL COMMENT '用电客户的行业分类代码,引用国标GB/T 4754-2002',
  `JLFSDM` varchar(8) NOT NULL COMMENT '主计量方式：1高供高计、2高供低计、3低供低计(是否需展示？)',
  `YHLBDM` varchar(8) NOT NULL COMMENT '用户一种常用的分类方式，方便用户的管理\r\n            01 公变用户，02 专变客户，03 线损考核，04 台区考核、05、购电',
  `GDDWBM` varchar(20) DEFAULT NULL COMMENT '供电单位编码',
  `CBQDBH` varchar(20) DEFAULT NULL COMMENT '用电客户所属的抄表区段。',
  `ZDYCXH` varchar(32) DEFAULT NULL COMMENT '存储客户提供的自己熟悉的一串标识码，客户通过各种服务渠道可以通过这个查询号来查询自己用电的信息，如客户有多个用电地址，可提供不同的查询号',
  `YYHBH` varchar(20) DEFAULT NULL COMMENT '原用户编号，用于系统升级的时候用户编号重新编号可以在一段时间内继续使用原用户编号查询用户信息',
  `HTRL` decimal(14,2) DEFAULT NULL COMMENT '合同约定的本用户的容量',
  `YXRL` decimal(14,2) DEFAULT NULL COMMENT '用电客户正在使用的合同容量，如暂停客户，在暂停期间其运行容量等于合同容量减去已暂停的容量',
  `SCBCDM` varchar(8) DEFAULT NULL COMMENT '用电客户的生产班次分类：单班，二班，三班，连续生产\r\n            ',
  `FHXZDM` varchar(8) DEFAULT NULL COMMENT '负荷的重要程度分类：一类，二类，三类\r\n            ',
  `GHNHYLBDM` varchar(8) DEFAULT NULL COMMENT '依据国家最新的高耗能行业划分',
  `CXR` varchar(32) DEFAULT NULL COMMENT '周休日通过数字连续表示周休哪几天，类似于飞机航班日期表示，如1.2.3,表示星期一星期二和星期三休息。\r\n            ',
  `LHRQ` datetime DEFAULT NULL COMMENT '电子用户档案的首次建立日期',
  `SDRQ` datetime DEFAULT NULL COMMENT '用户的首次送电日期',
  `XHRQ` datetime DEFAULT NULL COMMENT '销户业务信息归档的日期',
  `LSYDDQRQ` datetime DEFAULT NULL COMMENT '临时用电客户约定的用电到期日期',
  `LSYDBZ` varchar(8) DEFAULT NULL COMMENT '表示是否是临时用电的用电客户，且属于哪种临时用电\r\n            01 装表临时用电，02 无表临时用电，03 非临时用电',
  `YHZTDM` varchar(8) NOT NULL COMMENT '用电客户的状态说明，说明客户是否处于业扩变更中或已销户\r\n            ：正常用电客户，当前新装客户，当前变更客户，已销户客户。\r\n            ',
  `YDJCZQ` decimal(5,0) DEFAULT NULL COMMENT '检查周期(单位：月)：用于存放客户检查周期信息，便于周期检查计划制定时，获取参数。',
  `SCJCRQ` datetime DEFAULT NULL COMMENT '用电检查上次周期检查日期',
  `JCQDBS` varchar(16) DEFAULT NULL COMMENT '检查区段标识(增加)',
  `TDBZ` varchar(8) DEFAULT NULL COMMENT '停电标志：0 已停电  1 未停电，反映客户当前是否处于停电状态',
  `ZGLXDM` varchar(8) DEFAULT NULL COMMENT '标识客户是否是转供相关客户，如果涉及转供，是属于转供户还是被转供户：无转供，转供户，被转供户\r\n            ',
  `DQBM` varchar(8) NOT NULL COMMENT '用户所在的地区编码，用于分区。',
  `DYLXDM` varchar(8) DEFAULT NULL COMMENT '电源类型代码(单电源单回路、单电源双回路、双电源同站双回路、双电源异站双回路)',
  `DYLSFSDM` varchar(8) DEFAULT NULL COMMENT '电源之间的联锁方式\r\n            01 电气联锁、02 机械联锁、03 机械和电气联锁',
  `DYQHFSDM` varchar(8) DEFAULT NULL COMMENT '电源之间的切换方式\r\n            01 手动、02 自动',
  `DYLSZZWZ` varchar(256) DEFAULT NULL COMMENT '电源之间联锁装置的位置',
  `ZBDYBZ` varchar(8) DEFAULT NULL COMMENT '是否自备电源（是、否）',
  `ZBDYBSFSDM` varchar(8) DEFAULT NULL COMMENT '受电点的自备电源的闭锁方式代码：机械，电磁，电子，九线闸，其它\r\n            ',
  `ZBDYRL` decimal(14,2) DEFAULT NULL COMMENT '自备电源的总容量',
  `XBYHBZ` varchar(8) DEFAULT NULL COMMENT '是否谐波用户（是、否）',
  `CJFHYHBZ` varchar(8) DEFAULT NULL COMMENT '是否冲击负荷用户（是、否）',
  `GKKXBZ` varchar(8) DEFAULT NULL COMMENT '高可靠性标志（1是、0否）',
  `XZQYDM` varchar(16) DEFAULT NULL COMMENT '行政区域(所属村用该字段区分)',
  `CXDM` varchar(8) DEFAULT NULL COMMENT '城乡标志（城市、乡村）',
  `SZLC` decimal(5,0) DEFAULT NULL COMMENT '所在楼层',
  `YFFLXDM` varchar(8) DEFAULT NULL COMMENT '预付费类型（预售电、预付费、预收、非预付）',
  `LSJFGXH` varchar(20) DEFAULT NULL COMMENT '方便收费操作，用户间建立的松散的缴费关系的标识，可根据此编号缴费，系统显示该编号的所有用户欠费记录，但用户间不能互相共用余额(是否放在结算户上？)',
  `JCRYBS` varchar(32) DEFAULT NULL COMMENT '分管检查人员的人员标识，多个人员用'';''分开。(是否放用检？删除)',
  `CBSXH` decimal(5,0) DEFAULT NULL COMMENT '定义用户一个抄表区段的抄表顺序',
  `DWTYDZ` varchar(128) DEFAULT NULL COMMENT '单位通邮地址，业扩的作业知道书表单需要',
  `YZBM` varchar(6) DEFAULT NULL COMMENT '邮政编码，业务的作业指导书表单需要',
  `CZHM` varchar(32) DEFAULT NULL COMMENT '传真号码，业扩的作业指导书表单需要',
  `KHSFDM` varchar(8) DEFAULT NULL COMMENT '客户身份(业主、租户)，业扩的作业指导书表单需要',
  `KHFQBZ` varchar(8) DEFAULT NULL COMMENT '客服使用，对该用户进行分群，分为：重要客户、大客户、重点关注客户、居民客户、其它客户等五群客户。',
  `KHJLBS` varchar(32) DEFAULT NULL COMMENT '客服使用，记录用户对口服务的客户经理',
  `SFYZBDC` varchar(8) DEFAULT NULL COMMENT '是否有自备电厂，默认为“否”',
  `ZBDCRL` decimal(14,2) DEFAULT NULL COMMENT '自备电厂容量，现场勘查时录入',
  `BZFBZ` varchar(8) DEFAULT NULL COMMENT '保障房标志，受理时录入',
  `BZFZHS` decimal(10,0) DEFAULT NULL COMMENT '保障房总户数，受理时录入',
  `BZFZMJ` decimal(10,0) DEFAULT NULL COMMENT '保障房总面积，受理时录入',
  `BZFZRL` decimal(14,2) DEFAULT NULL COMMENT '保障房总容量，受理时录入',
  `CJSJ` datetime NOT NULL COMMENT '数据创建时间',
  `CZSJ` datetime NOT NULL COMMENT '数据最近一次变更时间',
  `CBZQ` varchar(8) DEFAULT NULL COMMENT '抄表周期(0_不抄表,1_每月一次抄表,2_单月抄表,3_双月抄表,4_每月多次抄表,5_不定期抄表)',
  `JTLX` varchar(8) DEFAULT NULL COMMENT '阶梯类型',
  `CDM` varchar(16) DEFAULT NULL COMMENT '村：农村电费公布榜需要',
  `SZXMBZ` varchar(8) DEFAULT NULL COMMENT '三重项目标志（是、否）',
  `SJZYBGSJ` datetime DEFAULT NULL COMMENT '数据资源管理平台变更时间',
  `YDJCSCZXJCRQ` datetime DEFAULT NULL COMMENT '用电检查上次专项检查日期',
  `GHRL` decimal(14,2) DEFAULT NULL COMMENT '规划容量',
  `BSZDSJ` datetime DEFAULT NULL COMMENT '补收终点时间',
  `ZTQMSJ` datetime DEFAULT NULL COMMENT '暂停期满时间点',
  `FKMSDM` varchar(8) DEFAULT NULL COMMENT '费控模式，包括：远程、本地、卡表',
  `FFMSDM` varchar(8) DEFAULT NULL COMMENT '付费模式，包括：后付，预付',
  `SFYXTDBZ` varchar(8) DEFAULT NULL COMMENT '是否允许停电标志，包括：是、否',
  `TDLXDM` varchar(8) DEFAULT NULL COMMENT '停电类型代码，包括：自动、手动',
  `FDFSDM` varchar(8) DEFAULT NULL COMMENT '复电方式代码，包括：远程、复电卡等',
  `JD` varchar(32) DEFAULT NULL COMMENT '经度',
  `WD` varchar(32) DEFAULT NULL COMMENT '纬度',
  `SFLDHBZ` varchar(8) DEFAULT NULL COMMENT '是否0度户标志',
  `SCJYYHBZ` varchar(8) DEFAULT NULL COMMENT '用电客户所属市场交易用户标志',
  `YHBZSXDM` varchar(8) DEFAULT NULL COMMENT '用户报装属性：01统一安装 02零散安装',
  PRIMARY KEY (`YHBH`),
  KEY `index_ydkh_yhbh` (`YHBH`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='该表存放用电客户和考核户、违约窃电黑户的基本信息\r\n1、用电客户定义：依法与供电企业建立供用电关系的组织或个人';

-- ----------------------------
-- Table structure for dl_lc_cbxx
-- ----------------------------
DROP TABLE IF EXISTS `dl_lc_cbxx`;
CREATE TABLE `dl_lc_cbxx` (
  `GZDBH` varchar(20) NOT NULL COMMENT '工作单编号',
  `JLDBH` varchar(20) NOT NULL COMMENT '计量点编号',
  `YXDNBBS` varchar(16) NOT NULL COMMENT '运行电能表标识',
  `SSLXDM` varchar(8) NOT NULL COMMENT '示数类型代码(正向有功总、正向有功尖峰等)',
  `YWLBDM` varchar(8) NOT NULL COMMENT '抄表业务类别代码(0_正常抄表,1_非周期及业扩变更结算抄表,2_补抄,3_政策性退补,4_监抄,5_试算等)',
  `JLDXH` decimal(5,0) DEFAULT NULL COMMENT '计量点序号',
  `SDLX` varchar(8) NOT NULL COMMENT '时段代码(冗余)',
  `CBJHBH` varchar(20) DEFAULT NULL COMMENT '抄表计划编号',
  `CBQDBH` varchar(20) DEFAULT NULL COMMENT '抄表区段编号',
  `JLDCBSXH` decimal(5,0) DEFAULT NULL COMMENT '计量点抄表顺序号',
  `CBSXH` decimal(5,0) DEFAULT NULL COMMENT '抄表顺序号',
  `ZFBBZ` varchar(8) DEFAULT NULL COMMENT '主副表标志(0_副表,1_主表)',
  `DFNY` decimal(6,0) NOT NULL COMMENT '电费年月',
  `BQCBCS` decimal(5,0) DEFAULT NULL COMMENT '本月抄表次数',
  `YCBCS` decimal(5,0) DEFAULT NULL COMMENT '应抄表次数',
  `CZCS` decimal(5,0) DEFAULT NULL COMMENT '冲正次数',
  `YHBH` varchar(20) DEFAULT NULL COMMENT '用户编号',
  `YHMC` varchar(128) DEFAULT NULL COMMENT '用户名称',
  `YDDZ` varchar(128) DEFAULT NULL COMMENT '用电地址',
  `JLDYTDM` varchar(8) DEFAULT NULL COMMENT '计量点用途代码',
  `ZCBH` varchar(32) DEFAULT NULL COMMENT '资产编号',
  `CCBH` varchar(32) DEFAULT NULL COMMENT '出厂编号',
  `SBLXDM` varchar(8) DEFAULT NULL COMMENT '设备类型代码',
  `SCBSS` decimal(13,5) DEFAULT NULL COMMENT '上次表示数',
  `BCBSS` decimal(13,5) DEFAULT NULL COMMENT '本次表示数',
  `BSSCE` decimal(13,5) DEFAULT NULL COMMENT '表示数差额',
  `BMWS` varchar(8) DEFAULT NULL COMMENT '表码位数',
  `XW` varchar(8) DEFAULT NULL COMMENT '相位',
  `ZHBL` decimal(12,3) NOT NULL COMMENT '综合倍率',
  `JBDL` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '旧表电量',
  `JJDL` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '加减电量',
  `YSDL` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '预收电量',
  `TBDL` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '退补电量',
  `SCYSDL` decimal(14,2) DEFAULT NULL COMMENT '上次预收电量',
  `BJDL` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '表计电量',
  `SCCBRQ` datetime DEFAULT NULL COMMENT '上次抄表日期',
  `SCBJDL` decimal(14,2) DEFAULT '0.00' COMMENT '上次表计电量',
  `PJBJDL` decimal(14,2) DEFAULT '0.00' COMMENT '上上次表计电量',
  `CBBZDM` varchar(8) NOT NULL DEFAULT '0' COMMENT '抄表标志代码(0_未抄,1_已抄)',
  `YHLBDM` varchar(8) DEFAULT NULL COMMENT '用户类别代码(用户一种常用的分类方式且方便用户的管理:1_公变用户,2_专变客户,3_线损考核,4_台区考核,5_购电)',
  `SJCBFSDM` varchar(8) DEFAULT NULL COMMENT '实际抄表方式代码(10_现场单户,11_手工(抄表卡),12_普通抄表器,13_远红外抄表器,20_现场集抄,21_普通抄表器集抄,22_远红外抄表器集抄,23_无线抄表器集抄,24_低压载波集抄,30_遥抄,31_负控遥抄,32_低压遥抄,33_配变遥抄,34_厂站遥抄,99_其它)',
  `CBZTDM` varchar(8) DEFAULT NULL COMMENT '抄表状态代码(0_正常,1_翻转,2_倒走等)',
  `CBYCDM` varchar(8) NOT NULL DEFAULT '00' COMMENT '抄表异常代码(0_无,10_示数不平,11_箱烂,12_违约,13_无表,14_电表烧表,15_电表故障,16_电表编号不符,18_变比不符,19_估抄,20_漏抄)',
  `GDDWBM` varchar(20) NOT NULL COMMENT '供电单位编码',
  `CBRBS` varchar(16) DEFAULT NULL COMMENT '抄表人标识',
  `CBSJ` datetime DEFAULT NULL COMMENT '抄表时间',
  `DJSJ` datetime DEFAULT NULL COMMENT '冻结时间',
  `SCGZDBH` varchar(20) DEFAULT NULL COMMENT '上次工作单编号',
  `DWBM` varchar(20) DEFAULT NULL COMMENT '单位编码',
  `DQBM` varchar(8) NOT NULL COMMENT '地区编码',
  `CJSJ` datetime NOT NULL COMMENT '数据创建时间',
  `CZSJ` datetime NOT NULL COMMENT '数据最近一次变更时间',
  `CZNY` decimal(6,0) DEFAULT NULL COMMENT '冲正年月',
  `SJLX` varchar(8) DEFAULT NULL COMMENT '数据类型',
  `YXBZ` varchar(8) DEFAULT NULL COMMENT '有效标志',
  `XZPDABZ` varchar(8) DEFAULT NULL COMMENT '下载PDA标志',
  `YCBH` varchar(20) DEFAULT NULL COMMENT '原抄表号,用于记录电能表上的抄表号',
  `ZWWCBBZ` varchar(8) DEFAULT NULL COMMENT '转外委抄表标志',
  `XXDM` varchar(8) DEFAULT NULL COMMENT '相线，包括：单相、三相三线、三相四线',
  `JLDCBFSDM` varchar(8) DEFAULT NULL COMMENT '计量点抄表方式代码',
  `ZDCBGXSJ` datetime DEFAULT NULL COMMENT '自动抄表更新时间',
  `YCCBBZ` varchar(8) DEFAULT NULL COMMENT '远程抄表标识',
  `JLQRLDBM` decimal(13,5) DEFAULT NULL COMMENT '计量前日0点表码',
  `JLDRLDBM` decimal(13,5) DEFAULT NULL COMMENT '计量当日0点表码',
  `JLDRESDBM` decimal(13,5) DEFAULT NULL COMMENT '计量当日24点表码',
  `JLCRESDBM` decimal(13,5) DEFAULT NULL COMMENT '计量次日24点表码',
  `SJCBRQ` datetime DEFAULT NULL COMMENT '实际抄表日期',
  `YCBCBZ` varchar(8) DEFAULT NULL COMMENT '远程自动化抄表存在补抄的情况，此字段标识获取的数据是否为计量系统补抄数据',
  PRIMARY KEY (`GZDBH`,`JLDBH`,`YXDNBBS`,`SSLXDM`,`YWLBDM`),
  KEY `index_cbxx_yhbh` (`YHBH`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='根据抄表计划和运行电能表等客户档案信息通过抄表数据开放形成的抄表信息及计费电量的存储';

-- ----------------------------
-- Table structure for dl_xt_dmbm
-- ----------------------------
DROP TABLE IF EXISTS `dl_xt_dmbm`;
CREATE TABLE `dl_xt_dmbm` (
  `DMBMBS` varchar(16) NOT NULL COMMENT '代码编码的唯一标识',
  `DMFLBS` varchar(16) NOT NULL COMMENT '代码分类的唯一标识',
  `SJDMBMBS` varchar(16) DEFAULT NULL COMMENT '上级代码编码标识，用来描述树形代码对应的上下级关系',
  `DMFL` varchar(16) DEFAULT NULL COMMENT '（冗余字段），方便数据查询',
  `DMBMNM` varchar(16) NOT NULL COMMENT '代码编码的内码，用来唯一标识代码编码（以代码分类为单位）',
  `DMBM` varchar(16) NOT NULL COMMENT '代码分类的编码内容，如紧急程度代码中：1 特急,2 紧急,3 一般',
  `DMBMMC` varchar(128) DEFAULT NULL COMMENT '代码分类的编码内容，如紧急程度代码中：1 特急,2 紧急,3 一般',
  `XSSX` decimal(5,0) DEFAULT NULL COMMENT '用于同一代码分类的排序',
  `KXBZ` varchar(8) NOT NULL COMMENT '可选标志，用于代码是否可选 如 0 否  1 是',
  `YYCJ1` varchar(32) DEFAULT NULL COMMENT '可选,用来根据应用场景筛选同一代码分类对应的编码内容，如电压等级的内容如下：01,750kV,变电站电压等级；02,500kV,变电站电压等级;03,220kV,变电站电压等级;04,110kV,变电站电压等级或高压用电;05,35kV,变电站电压等级或高压用电;06,20kV,高压用电;07,10kV,高压用电;08,380kV,低压用电;09,220kV,低压用电 ',
  `YYCJ2` varchar(32) DEFAULT NULL COMMENT '同应用场景1',
  `YYCJ3` varchar(32) DEFAULT NULL COMMENT '同应用场景1',
  `YYCJ4` varchar(32) DEFAULT NULL COMMENT '同应用场景1',
  `YYCJ5` varchar(32) DEFAULT NULL COMMENT '同应用场景1',
  `DZGX1` varchar(8) DEFAULT NULL COMMENT '可选，用来建立代码与代码分类之间的对照关系',
  `DZGX2` varchar(8) DEFAULT NULL COMMENT '可选，用来建立代码与代码分类之间的对照关系',
  `DZGX3` varchar(8) DEFAULT NULL COMMENT '可选，用来建立代码与代码分类之间的对照关系',
  `CJSJ` datetime NOT NULL COMMENT '数据创建时间',
  `CZSJ` datetime NOT NULL COMMENT '数据最近一次变更时间',
  PRIMARY KEY (`DMBMBS`),
  KEY `index_dmbm` (`DMBM`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='存放代码对应的编码内容';

-- ----------------------------
-- Table structure for dl_xt_zz
-- ----------------------------
DROP TABLE IF EXISTS `dl_xt_zz`;
CREATE TABLE `dl_xt_zz` (
  `ID` bigint(20) NOT NULL,
  `ZZBM` varchar(20) NOT NULL COMMENT '组织编码，当数据为单位时参照南网标准编码，数据为部门或者班组时由各单位根据编码规则自行编制',
  `ZZMC` varchar(128) NOT NULL COMMENT '组织名称的全称',
  `ZZJC` varchar(128) DEFAULT NULL COMMENT '组织名称的简称',
  `SJZZBM` varchar(20) DEFAULT NULL COMMENT '上级组织标识',
  `ZZLJ` varchar(256) NOT NULL COMMENT '存放记录在组织树的路径，用于提高上级组织查询下级组织数据时的性能',
  `DWBZ` varchar(8) NOT NULL COMMENT '是否单位标志，如 1是 0否 ，如不是单位，则为单位内部的部门或者班组',
  `ZZLXDM` varchar(8) NOT NULL COMMENT '组织类型代码，参见南网标准代码，如网、省、地市、供电所、班组等等',
  `ZYFLDM` varchar(64) DEFAULT NULL COMMENT '用于细分部门或者班组的专业分类，可适用于班组规范化管理、及角色授权时过滤使用，如 电费、抄表、装表、业扩等等',
  `XSSX` decimal(5,0) DEFAULT '0' COMMENT '组织展现时的排列顺序号',
  `ZTBZ` varchar(8) DEFAULT NULL COMMENT '状态标志，如在用、停用',
  `ZTRQ` datetime DEFAULT NULL COMMENT '状态日期',
  `BGDH` varchar(32) DEFAULT NULL COMMENT '办公电话',
  `BGDD` varchar(128) DEFAULT NULL COMMENT '办公地点',
  `CJRBS` varchar(16) DEFAULT NULL COMMENT '记录创建人的唯一标识',
  `DQBM` varchar(8) NOT NULL COMMENT '地区编码',
  `BZ` varchar(256) DEFAULT NULL COMMENT '备注',
  `CJSJ` datetime NOT NULL COMMENT '数据创建时间',
  `CZSJ` datetime NOT NULL COMMENT '数据最近一次变更时间',
  `KZZZBM` varchar(32) DEFAULT NULL COMMENT '4A主键组织编码（32位）大于南网的（20位），添加字段存放4A组织编码',
  `KZRYBS` varchar(32) DEFAULT NULL COMMENT '4A人员标识字段（32位）大于南网的（20位），添加字段存放4A人员标识',
  `KZSJZZBM` varchar(32) DEFAULT NULL COMMENT '4A上级组织编码（32位）大于南网的（20位），添加字段存放4A上级组织编码',
  `DWSXDM` varchar(8) DEFAULT NULL COMMENT '单位属性代码',
  `RZZZBM` varchar(32) DEFAULT NULL COMMENT '记录人力资源组织编码',
  PRIMARY KEY (`ID`),
  KEY `index_zzbm` (`ZZBM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='存放单位、部门、班组及其上下级关系，如广东电网公司、天河供电局、营销部、计量部、供电所等等';

-- ----------------------------
-- Table structure for dl_zw_ysdfjl
-- ----------------------------
DROP TABLE IF EXISTS `dl_zw_ysdfjl`;
CREATE TABLE `dl_zw_ysdfjl` (
  `YSZWLSH` varchar(16) NOT NULL COMMENT '应收账务流水号',
  `JLDBH` varchar(20) NOT NULL COMMENT '计量点编号',
  `JLDXH` decimal(5,0) DEFAULT NULL COMMENT '计量点序号',
  `GZDBH` varchar(20) DEFAULT NULL COMMENT '工作单编号',
  `CBQDBH` varchar(20) DEFAULT NULL COMMENT '抄表区段编号',
  `YHBH` varchar(20) DEFAULT NULL COMMENT '用户编号',
  `JSHH` varchar(20) DEFAULT NULL COMMENT '结算户号',
  `CBJHBH` varchar(20) DEFAULT NULL COMMENT '抄表计划编号',
  `DFNY` decimal(6,0) DEFAULT NULL COMMENT '电费年月',
  `BQCBCS` decimal(5,0) DEFAULT NULL COMMENT '本期抄表次数',
  `YCBCS` decimal(5,0) DEFAULT NULL COMMENT '应抄表次数',
  `JSLXDM` varchar(8) DEFAULT NULL COMMENT '结算类型代码(0_分次,1_结算)',
  `CZCS` decimal(5,0) DEFAULT NULL COMMENT '冲正次数(针对原记录:0_未被应收冲正,>1表示被冲正的次数)',
  `CZNY` decimal(6,0) DEFAULT NULL COMMENT '冲正年月(针对冲正红字记录)',
  `YXXBZ` varchar(8) NOT NULL COMMENT '有效性标志(0_否,1_是)',
  `YHMC` varchar(128) DEFAULT NULL COMMENT '用户名称',
  `YDDZ` varchar(128) DEFAULT NULL COMMENT '用电地址',
  `WYJRQ` datetime DEFAULT NULL COMMENT '违约金日期(违约金起征日期)',
  `HYFLDM` varchar(8) DEFAULT NULL COMMENT '行业分类代码(行业类别,目前使用国民经济行业分类与代码(GB/T 4754－2002),例如:01 农业 02林业 03畜牧业 04渔业)',
  `YHLBDM` varchar(8) DEFAULT NULL COMMENT '用户类别代码(1_公变用户,2_专变客户,3_线损考核,4_台区考核,5_购电)',
  `PJLXDM` varchar(8) DEFAULT NULL COMMENT '票据类型代码(0_普通发票,1_增值税发票)',
  `CXDM` varchar(8) DEFAULT NULL COMMENT '城乡代码(城乡标志:0_城市,1_乡村)',
  `YDLBDM` varchar(8) DEFAULT NULL COMMENT '用电类别代码',
  `DJDM` varchar(8) DEFAULT NULL COMMENT '电价代码',
  `DJ` decimal(10,6) DEFAULT NULL COMMENT '电价(主电价)',
  `FSJFBZ` varchar(8) DEFAULT NULL COMMENT '分时计费标志(是否执行峰谷标志:0_否,1_是)',
  `CCTBDL` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '差错退补电量',
  `JFDL` decimal(14,2) DEFAULT NULL COMMENT '计费电量',
  `DDDF` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '电度电费',
  `JBDF` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '基本电费',
  `LTDF` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '力调电费',
  `YSDF` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '应收电费',
  `FJFHJ` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '附加费合计',
  `CCTBDF` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '差错退补电费',
  `ZCTBDF` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '政策性退补电费',
  `JFYXJ` decimal(5,0) DEFAULT NULL COMMENT '缴费优先级，用于同一个结算户下多个计量点缴费的顺序',
  `PJDYXXBS` varchar(16) DEFAULT NULL COMMENT '票据流水号',
  `SFSCZDBZ` varchar(8) DEFAULT NULL COMMENT '是否生成账单数据的标志（0：否，1：是）',
  `ZDSCSJ` datetime DEFAULT NULL COMMENT '账单生成时间',
  `YWLBDM` varchar(8) DEFAULT NULL COMMENT '应收业务类别代码(0_正常电费,1_应收冲正[红字],2_冲正退补[蓝字],3_电量电费退补,4_政策性退补,5_窃电补收,6_窃电违约金,7_非周期性计费,8_卡表预售)',
  `SJLX` varchar(8) DEFAULT NULL COMMENT '包括 正常电费、冲正红字、冲正蓝字、差错电费等',
  `CDZXLDF` decimal(14,2) DEFAULT NULL COMMENT '超过需量定值电费',
  `JTLX` varchar(8) DEFAULT NULL COMMENT '阶梯类型',
  `JBDFJSFSDM` varchar(8) DEFAULT NULL COMMENT '基本电费计算方式代码',
  `MFDL` decimal(14,2) DEFAULT NULL COMMENT '免费电量',
  `FGZS` decimal(14,2) DEFAULT NULL COMMENT '峰谷增收',
  `FXRBS` varchar(16) DEFAULT NULL COMMENT '发行人标识',
  `FXSJ` datetime DEFAULT NULL COMMENT '发行时间',
  `GDDWBM` varchar(20) NOT NULL COMMENT '供电单位编码',
  `DWBM` varchar(20) DEFAULT NULL COMMENT '单位编码',
  `DQBM` varchar(8) NOT NULL COMMENT '地区编码',
  `CJSJ` datetime NOT NULL COMMENT '数据创建时间',
  `CZSJ` datetime NOT NULL COMMENT '数据最近一次变更时间',
  `DJBBBH` varchar(20) DEFAULT NULL COMMENT '计算参数版本的唯一标识，每次电价维护流程产生新版本',
  `JSHMC` varchar(128) DEFAULT NULL COMMENT '结算户名，发票打印抬头',
  `JSHDZ` varchar(128) DEFAULT NULL COMMENT '结算户地址，发票打印用',
  `FPDYFS` varchar(8) DEFAULT NULL COMMENT '发票打印方式：不打印、合打、按用户打、按计量点打',
  `FPHQFS` varchar(8) DEFAULT NULL COMMENT '发票获取方式，如派送、自取',
  `XLXDBS` varchar(16) DEFAULT NULL COMMENT '线路线段标识',
  `TQBS` varchar(16) DEFAULT NULL COMMENT '台区标识',
  `NLJDL` decimal(14,2) DEFAULT NULL COMMENT '年累计电量',
  `JHZDPSRQ` datetime DEFAULT NULL COMMENT '计划账单派送日期',
  `JHHKRQ` datetime DEFAULT NULL COMMENT '计划划扣日期',
  PRIMARY KEY (`YSZWLSH`,`JLDBH`),
  UNIQUE KEY `UIDX_ZW_YSDFJL` (`GZDBH`,`JLDXH`,`YWLBDM`),
  KEY `IDX_ZW_YSDFJL_JSHH_DFNY` (`JSHH`),
  KEY `IDX_ZW_YSDFJL_PJDYXXBS` (`PJDYXXBS`),
  KEY `IDX_ZW_YSDFJL_CBQDBH` (`CBQDBH`),
  KEY `IDX_ZW_YSDFJL_GDDWBM` (`GDDWBM`),
  KEY `IDX_ZW_YSDFJL_YHBH` (`YHBH`),
  KEY `IDX_ZW_YSDFJL_CBJHBH` (`CBJHBH`),
  KEY `IDX_ZW_YSDFJL_FXRBS` (`FXRBS`),
  KEY `IDX_ZW_YSDFJL_TQBS` (`TQBS`),
  KEY `IDX_ZW_YSDFJL_XLBS` (`XLXDBS`),
  KEY `IDX_ZW_YSDFJL_YWLBDM` (`YWLBDM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='存放应收电费记录';